analytics:
  google:
    id: UA-104944894-1

repository: swufer-home/swufer-home
repository_url: https://github.com/lawsons/home

timezone: Asia/Shanghai

name: 罗申导航 · Lawson-Home
author: Lawson-home
description: A Navigation Website for Lawson
keywords: 罗申导航, Lawson-home, Lawson, Navi, Navigation
url: https://lawsons.github.io/home

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
