analytics:
  google:
    id: UA-104944894-1

repository: swufer-home/swufer-home
repository_url: https://github.com/swufer-home/swufer-home

timezone: Asia/Shanghai

name: 苏菲导航 · Swufer-Home
author: Swufer-home
description: A Navigation Website for Swufer
keywords: 苏菲导航, Swufer-home, Swufer, Navi, Navigation, 西财, 西南财经大学
url: https://swufer-home.github.io/swufer-home

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
